version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      # bind-mount the model file from the host into the container so it can be changed without rebuilding
      - ./smart_home_model.pkl:/app/smart_home_model.pkl:ro

  dashboard:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - web
    environment:
      - BACKEND_URL=http://web:8000
    ports:
      - "8501:8501"

volumes:
  db_data:
